# Generated by Django 3.0.8 on 2020-07-14 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scheme',
            new_name='Schemes',
        ),
    ]
