# Generated by Django 3.0 on 2020-07-15 15:34

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0002_auto_20200714_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemes',
            name='Eligibility',
            field=jsonfield.fields.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schemes',
            name='Feature',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schemes',
            name='intermediator',
            field=jsonfield.fields.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schemes',
            name='needs',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schemes',
            name='Description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='schemes',
            name='Requirement',
            field=models.TextField(),
        ),
    ]
