# Generated by Django 2.2.3 on 2020-03-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='beneficiaries',
            fields=[
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('phoneno', models.IntegerField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('adhaarno', models.IntegerField(max_length=17, primary_key=True, serialize=False)),
                ('bankname', models.CharField(max_length=50)),
                ('accountno', models.IntegerField()),
                ('IFSC', models.CharField(max_length=50)),
                ('areafland', models.IntegerField()),
            ],
        ),
    ]
