# Generated by Django 2.2.3 on 2020-07-23 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sikkimgov', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intermediatorloginform',
            name='middlename',
        ),
        migrations.RemoveField(
            model_name='intermediatorloginform',
            name='mothername',
        ),
        migrations.RemoveField(
            model_name='intermediatorloginform',
            name='title',
        ),
    ]
