# Generated by Django 3.0.8 on 2020-08-02 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sikkimgov', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intermediatorloginform',
            name='adhaarimage',
        ),
    ]
