# Generated by Django 2.2.3 on 2020-07-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikkimgov', '0002_auto_20200307_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='intermediatorloginform',
            fields=[
                ('title', models.CharField(max_length=6)),
                ('firstname', models.CharField(max_length=20)),
                ('middlename', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('fathername', models.CharField(max_length=20)),
                ('mothername', models.CharField(max_length=20)),
                ('contactno', models.IntegerField(max_length=10)),
                ('alternatecontactno', models.IntegerField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('adhaarno', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('dateofbirth', models.DateField()),
            ],
        ),
    ]
