# Generated by Django 2.2.3 on 2020-07-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikkimgov', '0002_auto_20200724_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intermediatorlogin',
            name='intermediatorid',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='intermediatorlogin',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='userid',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
