# Generated by Django 3.0.8 on 2020-07-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikkimgov', '0003_auto_20200731_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaries',
            name='phase1',
            field=models.ImageField(blank=True, null=True, upload_to='phase1'),
        ),
        migrations.AddField(
            model_name='beneficiaries',
            name='phase2',
            field=models.ImageField(blank=True, null=True, upload_to='phase2'),
        ),
        migrations.AddField(
            model_name='beneficiaries',
            name='phase3',
            field=models.ImageField(blank=True, null=True, upload_to='phase3'),
        ),
        migrations.AddField(
            model_name='beneficiaries',
            name='phase4',
            field=models.ImageField(blank=True, null=True, upload_to='phase4'),
        ),
        migrations.AddField(
            model_name='beneficiaries',
            name='phase5',
            field=models.ImageField(blank=True, null=True, upload_to='phase5'),
        ),
        migrations.AddField(
            model_name='beneficiaries',
            name='phase6',
            field=models.ImageField(blank=True, null=True, upload_to='phase6'),
        ),
    ]
