# Generated by Django 2.2.3 on 2020-07-11 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sikkimgov', '0003_intermediatorloginform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intermediatorloginform',
            name='address',
        ),
    ]
