# Generated by Django 2.2.3 on 2020-07-11 13:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sikkimgov', '0004_remove_intermediatorloginform_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='intermediatorloginform',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='image'),
            preserve_default=False,
        ),
    ]
