# Generated by Django 2.2.3 on 2020-07-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikkimgov', '0005_intermediatorloginform_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intermediatorloginform',
            name='district',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
