# Generated by Django 2.2.3 on 2020-07-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikkimgov', '0006_auto_20200711_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intermediatorloginform',
            name='dateofbirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
