# Generated by Django 3.0.8 on 2020-07-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikkimgov', '0007_auto_20200711_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=500, unique=True)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='intermediatorloginform',
            name='alternatecontactno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='intermediatorloginform',
            name='contactno',
            field=models.IntegerField(),
        ),
    ]
