# Generated by Django 2.2.3 on 2020-07-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikkimgov', '0008_auto_20200714_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='intermediatorLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=500, unique=True)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='intermediatorloginform',
            name='image',
        ),
        migrations.AddField(
            model_name='beneficiaries',
            name='adhaarimage',
            field=models.ImageField(blank=True, null=True, upload_to='adhaarimage'),
        ),
        migrations.AddField(
            model_name='beneficiaries',
            name='registryimage',
            field=models.ImageField(blank=True, null=True, upload_to='registryimage'),
        ),
        migrations.AddField(
            model_name='intermediatorloginform',
            name='adhaarimage',
            field=models.ImageField(blank=True, null=True, upload_to='adhaarimage'),
        ),
    ]
