# Generated by Django 2.2.3 on 2020-07-19 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sikkimgov', '0009_auto_20200717_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intermediatorlogin',
            old_name='userid',
            new_name='intermediatorid',
        ),
    ]
