# Generated by Django 2.2.3 on 2020-07-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikkimgov', '0011_auto_20200720_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intermediatorlogin',
            name='intermediatorid',
            field=models.IntegerField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='intermediatorlogin',
            name='password',
            field=models.IntegerField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='password',
            field=models.IntegerField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='userid',
            field=models.IntegerField(max_length=500, unique=True),
        ),
    ]
